version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - joke_service
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URI=${DATABASE_URI}
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  joke_service:
    build: ./joke_service
    ports:
      - "5001:5001"